"""create_api_keys_table_and_modify_user_table

Revision ID: a3b59f0105a1
Revises: 9f0c9cd09105
Create Date: 2025-06-19 12:59:35.148977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from open_webui.internal.db import JSONField # Import JSONField if it's custom, otherwise use sa.JSON

# revision identifiers, used by Alembic.
revision: str = 'a3b59f0105a1'
down_revision: Union[str, None] = '9f0c9cd09105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True), # Default handled by model
    sa.Column('last_used_at', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('info', JSONField, nullable=True), # Use imported JSONField
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    # Re-create unique constraint if it existed. Check your original schema.
    # op.create_unique_constraint('user_api_key_key', 'user', ['api_key']) # Example if it was named user_api_key_key
    op.drop_table('apikey')
    # ### end Alembic commands ###
